## 1. What is a Python library? Why do we use Python libraries?

A Python library is a collection of functions and methods that allow you to perform specific tasks without having to write the code from scratch. Python libraries provide pre-written code that can be imported into your Python scripts, saving you time and effort in development.

We use Python libraries to leverage existing code and functionality for various purposes, such as data manipulation, data visualization, machine learning, web development, scientific computing, and more. By using libraries, we can streamline our development process, increase efficiency, and build more complex and advanced applications with ease. Python libraries also promote code reusability, collaboration, and community-driven development in the Python programming ecosystem.

## 2. What is the difference between Numpy array and List?

A NumPy array is a grid of values, all of the same type, and is indexed by a tuple of non-negative integers. It is one of the fundamental data structures in NumPy, which stands for Numerical Python. NumPy arrays are more efficient in terms of storage and performance compared to Python lists because they are implemented in C. They also support various mathematical operations and functions optimized for numerical computations.

On the other hand, a list in Python is a collection of heterogeneous elements, meaning it can contain values of different data types. Lists are more flexible and versatile compared to NumPy arrays because they can store any type of data. However, lists are slower in terms of performance and efficiency when it comes to large datasets or numerical computations.

In summary, the key differences between a NumPy array and a list are efficiency, performance, data type restriction, and functionality for numerical computations.

## 3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [4]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Shape
print("Shape:", arr.shape)

# Size
print("Size:", arr.size)

# Dimension
print("Dimension:", arr.ndim)

Shape: (3, 4)
Size: 12
Dimension: 2


## 4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [5]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Accessing the first row
first_row = arr[0]

print("First Row:", first_row)

First Row: [1 2 3 4]


## 5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [10]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print("The array is: ", arr)

# Accessing the element at the third row and fourth column
element = arr[2, 3]

print("Element at the third row and fourth column:", element)


The array is:  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Element at the third row and fourth column: 12


## 6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [12]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr)
# Extracting odd-indexed elements
odd_indexed_elements = arr[:, 1::2].flatten()

print("Odd-indexed elements:", odd_indexed_elements)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Odd-indexed elements: [ 2  4  6  8 10 12]


## 7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [13]:
import numpy as np

# Generate a random 3x3 matrix with values between 0 and 1
random_matrix = np.random.rand(3, 3)

print("Random 3x3 Matrix with values between 0 and 1:")
print(random_matrix)

Random 3x3 Matrix with values between 0 and 1:
[[0.50685947 0.67349692 0.79012058]
 [0.85686246 0.18330692 0.82474529]
 [0.41562447 0.69230486 0.98144673]]


## 8. Describe the difference between np.random.rand and np.random.randn?

The main difference between np.random.rand and np.random.randn in NumPy lies in how they generate random numbers.

np.random.rand generates random numbers between 0 and 1 from a uniform distribution, meaning that each number has an equal probability of being selected within the specified range. It takes shape as input and returns an array of random numbers with the specified shape.

On the other hand, np.random.randn generates random numbers from a standard normal distribution with a mean of 0 and a standard deviation of 1. This distribution is also known as the Gaussian distribution. It takes the dimensions as input and returns an array of random numbers with the specified shape following the standard normal distribution.

9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [14]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Increase the dimension of the array
new_arr = np.expand_dims(arr, axis=0)

print("Array with increased dimension:")
print(new_arr)

Array with increased dimension:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]


In [15]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Transpose the array
transposed_arr = arr.T

print("Transposed Array:")
print(transposed_arr)

Transposed Array:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


11. Consider the following matrix:
Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Perform the following operation using Python
1. Index wise multiplication
2. Matrix multiplication
3. Add both the matrics
4. Subtract matrix B from A
5. Divide Matrix B by A

In [16]:
import numpy as np

A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
B = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Index-wise multiplication
index_wise_product = A * B

print("Index-wise Multiplication Result:")
print(index_wise_product)

# Matrix multiplication
matrix_product = np.dot(A, B.T)

print("Matrix Multiplication Result:")
print(matrix_product)

# Add both matrices
matrix_sum = A + B

print("Sum of Matrices:")
print(matrix_sum)

# Subtract matrix B from A
matrix_diff = A - B

print("Difference of Matrices:")
print(matrix_diff)

# Divide Matrix B by A
matrix_div = B / A

print("Division of Matrices:")
print(matrix_div)


Index-wise Multiplication Result:
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
Matrix Multiplication Result:
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]
Sum of Matrices:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
Difference of Matrices:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Division of Matrices:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## 12. Which function in Numpy can be used to swap the byte order of an array?

In [17]:
'''To swap the byte order of an array in NumPy, you can use the byteswap() function. This function allows 
you to change the byte order of the elements in the array. By calling byteswap(), you can swap the byte 
order of the array and manipulate the endianness of the data stored in the array.'''

import numpy as np

# Create an example array
arr = np.array([1, 2, 3, 4], dtype=np.int32)

# Swap the byte order of the array
swapped_arr = arr.byteswap()

print("Swapped Array:")
print(swapped_arr)

Swapped Array:
[16777216 33554432 50331648 67108864]


## 13. What is the significance of the np.linalg.inv function?

In [24]:
'''The np.linalg.inv function in NumPy is used to compute the multiplicative inverse of a matrix. It is 
significant in various mathematical and scientific computations, especially in linear algebra.

When you apply np.linalg.inv to a square matrix, it calculates the inverse of that matrix, which can be 
helpful in solving systems of linear equations, finding determinants, and performing various matrix 
operations. The inverse of a matrix A, denoted as A^-1, has the property that A * A^-1 = I, where I is 
the identity matrix.

By using np.linalg.inv, you can effectively invert a matrix and perform operations like solving linear 
equations or finding the pseudo-inverse of a matrix. This function is crucial in numerous numerical 
computations and plays a key role in many applications across different fields such as engineering, physics, 
and machine learning.'''


import numpy as np

# Define a square matrix
A = np.array([[1, 2],
              [3, 4]])

# Calculate the inverse of the matrix
A_inv = np.linalg.inv(A)

# Print the original matrix and its inverse
print("Original Matrix A:")
print(A)
print("\nInverse of Matrix A:")
print(A_inv)

Original Matrix A:
[[1 2]
 [3 4]]

Inverse of Matrix A:
[[-2.   1. ]
 [ 1.5 -0.5]]


## 14. What does the np.reshape function do, and how is it used?

The np.reshape function in NumPy is used to change the shape of an array without changing its data. It allows you to specify the new shape of the array, ensuring that the total number of elements remains constant after reshaping.

By using np.reshape, you can convert a 1D array into a 2D array, or reshape a 2D array into a different shape, such as turning a matrix into a vector. This function is particularly handy in tasks involving image processing, data manipulation, and machine learning, where the shape of the data needs to be adjusted for further analysis or processing.

In [25]:
import numpy as np

# Create a 1D array
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array into a 2D array of shape (2, 3)
reshaped_arr = np.reshape(arr, (2, 3))

print("Original Array:")
print(arr)

print("Reshaped Array:")
print(reshaped_arr)


Original Array:
[1 2 3 4 5 6]
Reshaped Array:
[[1 2 3]
 [4 5 6]]


## 15. What is broadcasting in Numpy?

Broadcasting in NumPy is a powerful concept that allows arrays of different shapes to be combined in arithmetic operations. When performing element-wise operations between two arrays, NumPy automatically broadcasts the arrays to have compatible shapes before carrying out the operation.

In broadcasting, NumPy compares the shapes of the input arrays element-wise, starting from the trailing dimensions and working backward. Two dimensions are considered compatible if they are equal or if one of them is 1. If the dimensions are not compatible, NumPy replicates the array with the smaller dimension to match the shape of the larger array.

This broadcasting mechanism simplifies operations and makes code more concise by removing the need for explicit loops or repetitive code. It improves the efficiency of numerical computations by avoiding unnecessary memory allocations and making use of optimized C code for array operations.

In [26]:
import numpy as np

# Create two arrays of different shapes
arr1 = np.array([[1], [2], [3]])
arr2 = np.array([4, 5, 6])

# Perform element-wise addition using broadcasting
result = arr1 + arr2

print("Array 1:")
print(arr1)

print("Array 2:")
print(arr2)

print("Result after broadcasting:")
print(result)


Array 1:
[[1]
 [2]
 [3]]
Array 2:
[4 5 6]
Result after broadcasting:
[[5 6 7]
 [6 7 8]
 [7 8 9]]


<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=856fd44e-82f5-4be9-ace6-ff183ee3aff3' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>